/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import java.awt.Image;
import java.net.URL;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class AddListaJogoPanel extends javax.swing.JPanel {
    private Jogo jogo;
    private User usuario;
    ImageIcon plusSign;
    ImageIcon check;
    boolean escolhido;
    List<String> escolhidos;
    
    /**
     * Creates new form JogoPanel
     */
    public AddListaJogoPanel(Jogo jogo, User u, List<String> escolhidos) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/plus.png"));
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        plusSign = new ImageIcon(newImage);
        
        icon = new ImageIcon(getClass().getResource("/images/check.png"));
        image = icon.getImage();
        newImage = image.getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        check = new ImageIcon(newImage);
        
        this.escolhido = escolhidos.contains(jogo.getNome());
        this.escolhidos = escolhidos;
        this.jogo = jogo;
        this.usuario = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogo_icon = new javax.swing.JLabel();
        jogo_tittle = new javax.swing.JLabel();
        jogo_descr = new javax.swing.JLabel();
        btn_plus = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 244, 244), 6));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(660, 110));
        setMinimumSize(new java.awt.Dimension(660, 110));
        setPreferredSize(new java.awt.Dimension(660, 110));

        try {
            URL url = new URL(jogo.getImg());
            Image image = ImageIO.read(url);
            Image newImage = image.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(newImage);
            jogo_icon.setIcon(icon);
        } catch(Exception e) {}
        jogo_icon.setMaximumSize(new java.awt.Dimension(80, 80));
        jogo_icon.setMinimumSize(new java.awt.Dimension(80, 80));
        jogo_icon.setPreferredSize(new java.awt.Dimension(80, 80));

        jogo_tittle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jogo_tittle.setText(jogo.getNome());

        jogo_descr.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jogo_descr.setText("<html><p style=\"width:450px\">"+jogo.getDescr()+"</p></html>");
        jogo_descr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jogo_descr.setMaximumSize(new java.awt.Dimension(557, 47));
        jogo_descr.setMinimumSize(new java.awt.Dimension(557, 47));
        jogo_descr.setPreferredSize(new java.awt.Dimension(557, 47));

        btn_plus.setIcon((escolhido ? check : plusSign));
        btn_plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_plusMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jogo_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jogo_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jogo_descr, javax.swing.GroupLayout.PREFERRED_SIZE, 463, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jogo_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jogo_descr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jogo_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_plusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_plusMouseReleased
        if(escolhido) {
            btn_plus.setIcon(plusSign);
            escolhidos.remove(jogo.getNome());
            escolhido = false;
        } else {
            btn_plus.setIcon(check);
            escolhidos.add(jogo.getNome());
            escolhido = true;
        }
    }//GEN-LAST:event_btn_plusMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_plus;
    private javax.swing.JLabel jogo_descr;
    private javax.swing.JLabel jogo_icon;
    private javax.swing.JLabel jogo_tittle;
    // End of variables declaration//GEN-END:variables
}