/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import View.JogoFrame;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class AvaliacaoPanel extends javax.swing.JPanel {
    private Avaliacao avaliacao;
    
    /**
     * Creates new form JogoPanel
     */
    public AvaliacaoPanel(Avaliacao avaliacao) {
        this.avaliacao = avaliacao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliacao_icon = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        avaliacao_comentario = new javax.swing.JLabel();
        avaliacao_nota = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 244, 244), 6));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(660, 110));
        setMinimumSize(new java.awt.Dimension(660, 110));
        setPreferredSize(new java.awt.Dimension(660, 110));

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/default_pfp.jpg"));
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
        icon = new ImageIcon(newImage);
        avaliacao_icon.setIcon(icon);

        avaliacao_icon.setMaximumSize(new java.awt.Dimension(80, 80));
        avaliacao_icon.setMinimumSize(new java.awt.Dimension(80, 80));
        avaliacao_icon.setPreferredSize(new java.awt.Dimension(80, 80));

        username.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        username.setText(avaliacao.getUsername());
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        avaliacao_comentario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        avaliacao_comentario.setText("<html><p style=\"width:450px\">"+(avaliacao.getComentario() == "" ? "..." : avaliacao.getComentario())+"</p></html>");
        avaliacao_comentario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        avaliacao_comentario.setMaximumSize(new java.awt.Dimension(557, 47));
        avaliacao_comentario.setMinimumSize(new java.awt.Dimension(557, 47));
        avaliacao_comentario.setPreferredSize(new java.awt.Dimension(557, 47));

        avaliacao_nota.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        avaliacao_nota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avaliacao_nota.setText(String.valueOf(avaliacao.getNota()) + "/10");
        avaliacao_nota.setMaximumSize(new java.awt.Dimension(660, 110));
        avaliacao_nota.setMinimumSize(new java.awt.Dimension(660, 110));
        avaliacao_nota.setName(""); // NOI18N
        avaliacao_nota.setPreferredSize(new java.awt.Dimension(660, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(avaliacao_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avaliacao_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(avaliacao_comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 541, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username)
                            .addComponent(avaliacao_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avaliacao_comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(avaliacao_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avaliacao_comentario;
    private javax.swing.JLabel avaliacao_icon;
    private javax.swing.JLabel avaliacao_nota;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
