/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import View.JogoFrame;
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo
 */
public class JogoPanel extends javax.swing.JPanel {
    private Jogo jogo;
    private User usuario;
    
    /**
     * Creates new form JogoPanel
     */
    public JogoPanel(Jogo jogo, User u) {
        this.jogo = jogo;
        this.usuario = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogo_icon = new javax.swing.JLabel();
        jogo_tittle = new javax.swing.JLabel();
        jogo_descr = new javax.swing.JLabel();
        jogo_nota = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 244, 244), 6));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(660, 110));
        setMinimumSize(new java.awt.Dimension(660, 110));
        setPreferredSize(new java.awt.Dimension(660, 110));

        try {
            URL url = new URL(jogo.getImg());
            Image image = ImageIO.read(url);
            Image newImage = image.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(newImage);
            jogo_icon.setIcon(icon);
        } catch(Exception e) {}

        jogo_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogo_icon.setMaximumSize(new java.awt.Dimension(80, 80));
        jogo_icon.setMinimumSize(new java.awt.Dimension(80, 80));
        jogo_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        jogo_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jogo_iconMouseReleased(evt);
            }
        });

        jogo_tittle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jogo_tittle.setText(jogo.getNome());
        jogo_tittle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogo_tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jogo_tittleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jogo_tittleMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jogo_tittleMouseReleased(evt);
            }
        });

        jogo_descr.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jogo_descr.setText("<html><p style=\"width:450px\">"+jogo.getDescr()+"</p></html>");
        jogo_descr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jogo_descr.setMaximumSize(new java.awt.Dimension(557, 47));
        jogo_descr.setMinimumSize(new java.awt.Dimension(557, 47));
        jogo_descr.setPreferredSize(new java.awt.Dimension(557, 47));

        jogo_nota.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jogo_nota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jogo_nota.setText(String.format("%.1f/10", jogo.getNota()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jogo_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jogo_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jogo_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jogo_descr, javax.swing.GroupLayout.PREFERRED_SIZE, 541, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jogo_tittle)
                            .addComponent(jogo_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jogo_descr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jogo_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jogo_tittleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_tittleMouseEntered
        jogo_tittle.setText("<HTML><U>"+jogo.getNome()+"</U></HTML>");
    }//GEN-LAST:event_jogo_tittleMouseEntered

    private void jogo_tittleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_tittleMouseExited
        jogo_tittle.setText(jogo.getNome());
    }//GEN-LAST:event_jogo_tittleMouseExited

    private void jogo_tittleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_tittleMouseReleased
        new JogoFrame(jogo, usuario);
    }//GEN-LAST:event_jogo_tittleMouseReleased

    private void jogo_iconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_iconMouseReleased
        new JogoFrame(jogo, usuario);
    }//GEN-LAST:event_jogo_iconMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jogo_descr;
    private javax.swing.JLabel jogo_icon;
    private javax.swing.JLabel jogo_nota;
    private javax.swing.JLabel jogo_tittle;
    // End of variables declaration//GEN-END:variables
}
