/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import Controller.Controller;
import View.JogoFrame;
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class ListaJogoPanel extends javax.swing.JPanel {
    private Jogo jogo;
    private User usuario;
    private ImageIcon trashIcon;
    private int listaId;
    
    /**
     * Creates new form JogoPanel
     */
    public ListaJogoPanel(Jogo jogo, User u, int listaId) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/delete.png"));
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        trashIcon = new ImageIcon(newImage);
        
        this.listaId = listaId;
        this.jogo = jogo;
        this.usuario = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogo_icon = new javax.swing.JLabel();
        jogo_tittle = new javax.swing.JLabel();
        jogo_descr = new javax.swing.JLabel();
        btn_trash = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 244, 244), 6));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(660, 110));
        setMinimumSize(new java.awt.Dimension(660, 110));
        setPreferredSize(new java.awt.Dimension(660, 110));

        try {
            URL url = new URL(jogo.getImg());
            Image image = ImageIO.read(url);
            Image newImage = image.getScaledInstance(80, 80, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(newImage);
            jogo_icon.setIcon(icon);
        } catch(Exception e) {}
        jogo_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogo_icon.setMaximumSize(new java.awt.Dimension(80, 80));
        jogo_icon.setMinimumSize(new java.awt.Dimension(80, 80));
        jogo_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        jogo_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jogo_iconMouseReleased(evt);
            }
        });

        jogo_tittle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jogo_tittle.setText(jogo.getNome());
        jogo_tittle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogo_tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jogo_tittleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jogo_tittleMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jogo_tittleMouseReleased(evt);
            }
        });

        jogo_descr.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jogo_descr.setText("<html><p style=\"width:450px\">"+jogo.getDescr()+"</p></html>");
        jogo_descr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jogo_descr.setMaximumSize(new java.awt.Dimension(557, 47));
        jogo_descr.setMinimumSize(new java.awt.Dimension(557, 47));
        jogo_descr.setPreferredSize(new java.awt.Dimension(557, 47));

        btn_trash.setIcon(trashIcon);
        btn_trash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_trash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_trashMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jogo_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jogo_descr, javax.swing.GroupLayout.PREFERRED_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jogo_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jogo_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jogo_descr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jogo_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trashMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trashMouseReleased
        int res = JOptionPane.showConfirmDialog(
                        null,
                        "Tem certeza que deseja deletar "+jogo.getNome()+" de sua lista?",
                        "Sair",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );
        
        if(res == 0) {
           Controller.getController().deleteFromLista(jogo, listaId);
        } else {}
    }//GEN-LAST:event_btn_trashMouseReleased

    private void jogo_iconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_iconMouseReleased
        new JogoFrame(jogo, usuario);
    }//GEN-LAST:event_jogo_iconMouseReleased

    private void jogo_tittleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_tittleMouseEntered
        jogo_tittle.setText("<HTML><U>"+jogo.getNome()+"</U></HTML>");
    }//GEN-LAST:event_jogo_tittleMouseEntered

    private void jogo_tittleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_tittleMouseExited
        jogo_tittle.setText(jogo.getNome());
    }//GEN-LAST:event_jogo_tittleMouseExited

    private void jogo_tittleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogo_tittleMouseReleased
        new JogoFrame(jogo, usuario);
    }//GEN-LAST:event_jogo_tittleMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_trash;
    private javax.swing.JLabel jogo_descr;
    private javax.swing.JLabel jogo_icon;
    private javax.swing.JLabel jogo_tittle;
    // End of variables declaration//GEN-END:variables
}