/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model;

import Controller.Controller;
import View.ListaFrame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class ListaPanel extends javax.swing.JPanel {
    private Lista lista;
    private User usuario;
    
    /**
     * Creates new form JogoPanel
     */
    public ListaPanel(Lista lista, User u) {
        this.lista = lista;
        this.usuario = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista_tittle = new javax.swing.JLabel();
        trash_icon = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 244, 244), 6));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(670, 60));
        setMinimumSize(new java.awt.Dimension(670, 60));
        setPreferredSize(new java.awt.Dimension(670, 60));

        lista_tittle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lista_tittle.setText(lista.getNome());
        lista_tittle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lista_tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lista_tittleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lista_tittleMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lista_tittleMouseReleased(evt);
            }
        });

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/delete.png"));
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(30, 30, Image.SCALE_DEFAULT);
        icon = new ImageIcon(newImage);
        trash_icon.setIcon(icon);
        trash_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trash_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                trash_iconMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lista_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trash_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lista_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trash_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lista_tittleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_tittleMouseEntered
        lista_tittle.setText("<HTML><U>"+lista.getNome()+"</U></HTML>");
    }//GEN-LAST:event_lista_tittleMouseEntered

    private void lista_tittleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_tittleMouseExited
        lista_tittle.setText(lista.getNome());
    }//GEN-LAST:event_lista_tittleMouseExited

    private void lista_tittleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_tittleMouseReleased
        new ListaFrame(this.lista, usuario);
    }//GEN-LAST:event_lista_tittleMouseReleased

    private void trash_iconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trash_iconMouseReleased
        int res = JOptionPane.showConfirmDialog(
                        null,
                        "Tem certeza que deseja excluir a lista "+lista.getNome()+"?",
                        "Exluir lista",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );
        if(res == 0) {
            Controller.getController().deleteLista(lista);
        } else {}
    }//GEN-LAST:event_trash_iconMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lista_tittle;
    private javax.swing.JLabel trash_icon;
    // End of variables declaration//GEN-END:variables
}
