/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.CadastroException;
import Controller.Controller;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class Cadastro extends javax.swing.JFrame {
    private static Cadastro cadastroUnic;
    private static Controller c;
    
    /**
     * Creates new form NewJFrame
     */
    private Cadastro() {
        c = Controller.getController();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static Cadastro getCadastro() {
        if(cadastroUnic == null) {
            cadastroUnic = new Cadastro();
        }
        
        return cadastroUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_logar = new javax.swing.JButton();
        cadastro_tittle = new javax.swing.JLabel();
        nome_textfield = new javax.swing.JTextField();
        nome_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        senha_label = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        username_textfield = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        senha_textfield = new javax.swing.JPasswordField();

        btn_logar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_logar.setText("Logar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setMaximumSize(new java.awt.Dimension(700, 480));
        setMinimumSize(new java.awt.Dimension(700, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cadastro_tittle.setFont(new java.awt.Font("Monospaced", 1, 72)); // NOI18N
        cadastro_tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastro_tittle.setText("Cadastro");

        nome_textfield.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        nome_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nome_label.setText("Nome:");

        email_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        email_label.setText("E-mail:");

        senha_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        senha_label.setText("Senha:");

        email_textfield.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        btn_cadastrar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        username_textfield.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        username_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        username_label.setText("Nome de usuário:");

        senha_textfield.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastro_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_label)
                    .addComponent(nome_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_label)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senha_label)
                    .addComponent(email_label)
                    .addComponent(email_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(senha_textfield))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cadastro_tittle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nome_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(username_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(senha_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senha_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(btn_cadastrar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        GameBoxd.getGameBoxd().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        if(username_textfield.getText().equals("") || String.valueOf(senha_textfield.getPassword()).equals("") ||
           nome_textfield.getText().equals("") || email_textfield.getText().equals("")) {
            JOptionPane.showMessageDialog(
                        null,
                        "Preencha todos os campos.",
                        "Aviso!",
                        JOptionPane.WARNING_MESSAGE
                );
        } else if(username_textfield.getText().contains(" ") || email_textfield.getText().contains(" ")) {
            JOptionPane.showMessageDialog(
                        null,
                        "Nome de usuário e email não podem ter espaços.",
                        "Aviso!",
                        JOptionPane.WARNING_MESSAGE
                );
        } else {
            try {
                c.tryCadastro(username_textfield.getText(), nome_textfield.getText(), String.valueOf(senha_textfield.getPassword()), email_textfield.getText());
                JOptionPane.showMessageDialog(
                        null,
                        "Cadastro realizado com sucesso!.",
                        "Sucesso!",
                        JOptionPane.PLAIN_MESSAGE
                );
                username_textfield.setText("");
                nome_textfield.setText("");
                senha_textfield.setText("");
                email_textfield.setText("");
                this.dispose();
                Login.getLogin().setVisible(true);
            } catch(CadastroException e) {
                JOptionPane.showMessageDialog(
                        null,
                        e.getMessage(),
                        "Erro!",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_logar;
    private javax.swing.JLabel cadastro_tittle;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel nome_label;
    private javax.swing.JTextField nome_textfield;
    private javax.swing.JLabel senha_label;
    private javax.swing.JPasswordField senha_textfield;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
