/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import Model.BuscaException;
import Model.Jogo;
import Model.AddListaJogoPanel;
import Model.User;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class CreateListFrame extends javax.swing.JFrame {
    private User u;
    private Controller c;
    private List<Jogo> jogos;
    private List<String> escolhidos;
    private javax.swing.JPanel view;
    
    /**
     * Creates new form CreateListFrame
     */
    public CreateListFrame(User u) {
        this.c = Controller.getController();
        this.u = u;
        this.view = new javax.swing.JPanel();
        this.view.setLayout(new BoxLayout(this.view, BoxLayout.Y_AXIS));
        this.view.setBackground(new Color(244,244,244));
        this.escolhidos = new ArrayList<String>();
        jogos = c.getJogos();
        refresh();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void refresh() {
        view.removeAll();
        view.revalidate();
        view.repaint();
        for(Jogo j : jogos) {
            view.add(new AddListaJogoPanel(j, u, escolhidos));
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome_lista_field = new javax.swing.JTextField();
        barraDePesquisa_textfield = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane(this.view);
        jLabel3 = new javax.swing.JLabel();
        btn_criar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar lista");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 72)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criar Lista");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome da lista");

        nome_lista_field.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        barraDePesquisa_textfield.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        btn_buscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adicionar jogos");

        btn_criar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_criar.setText("Criar lista");
        btn_criar.setToolTipText("");
        btn_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(btn_criar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(barraDePesquisa_textfield)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nome_lista_field)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_lista_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraDePesquisa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_criar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if(barraDePesquisa_textfield.getText().equals("")) {
            jogos = c.getJogos();
        } else {
            try {
                jogos = c.buscaJogos(barraDePesquisa_textfield.getText());
            } catch(BuscaException e) {
                JOptionPane.showMessageDialog(
                            null,
                            e.getMessage(),
                            "Erro!",
                            JOptionPane.ERROR_MESSAGE
                    );
            }
        }
        
        refresh();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarActionPerformed
        if(nome_lista_field.getText().equals("")) {
            JOptionPane.showMessageDialog(
                        null,
                        "Coloque um nome na sua lista!",
                        "Aviso!",
                        JOptionPane.WARNING_MESSAGE
                );
        } else {
            c.criarLista(nome_lista_field.getText(), u, escolhidos);
            JOptionPane.showMessageDialog(
                        null,
                        "Lista criada com sucesso!",
                        "Aviso!",
                        JOptionPane.PLAIN_MESSAGE
                );
            this.dispose();
        }
    }//GEN-LAST:event_btn_criarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraDePesquisa_textfield;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_criar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField nome_lista_field;
    // End of variables declaration//GEN-END:variables
}
