/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.User;
import Controller.Controller;
import Model.BuscaException;
import Model.Jogo;
import Model.JogoPanel;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class Home extends javax.swing.JFrame {
    private Controller c;
    private User u;
    private List<Jogo> jogos;
    private javax.swing.JPanel view;

    /**
     * Creates new form Home
     * @param usuario
     */
    public Home(User usuario) {
        this.c = Controller.getController();
        this.u = usuario;
        this.view = new javax.swing.JPanel();
        this.view.setLayout(new BoxLayout(this.view, BoxLayout.Y_AXIS));
        this.view.setBackground(new Color(244,244,244));
        jogos = c.getJogos();
        refresh();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void refresh() {
        view.removeAll();
        view.revalidate();
        view.repaint();
        for(Jogo j : jogos) {
            view.add(new JogoPanel(j, u));
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameboxd_tittle = new javax.swing.JLabel();
        barraDePesquisa_textfield = new javax.swing.JTextField();
        jogos_scrollPane = new javax.swing.JScrollPane(this.view);
        btn_buscar = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        conta_menuItem = new javax.swing.JMenuItem();
        listas_menuItem = new javax.swing.JMenuItem();
        minhasAvaliacoes_menuItem = new javax.swing.JMenuItem();
        adm_menu = new javax.swing.JMenu();
        addJogo_menuItem = new javax.swing.JMenuItem();
        removerJogo_menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GameBoxd");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        gameboxd_tittle.setFont(new java.awt.Font("Monospaced", 1, 72)); // NOI18N
        gameboxd_tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameboxd_tittle.setText("GameBoxd");

        jogos_scrollPane.setMaximumSize(new java.awt.Dimension(688, 306));
        jogos_scrollPane.setMinimumSize(new java.awt.Dimension(688, 306));
        jogos_scrollPane.setPreferredSize(new java.awt.Dimension(688, 306));

        btn_buscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Menu");

        conta_menuItem.setText("Minha conta ("+this.u.getUsername()+")");
        conta_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conta_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(conta_menuItem);

        listas_menuItem.setText("Minhas Listas");
        listas_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listas_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(listas_menuItem);

        minhasAvaliacoes_menuItem.setText("Minhas avaliacoes");
        minhasAvaliacoes_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasAvaliacoes_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(minhasAvaliacoes_menuItem);

        Menu.add(jMenu1);
        if(u.getUsername().equals("adm")) {
            adm_menu = new javax.swing.JMenu();
            addJogo_menuItem = new javax.swing.JMenuItem();
            removerJogo_menuItem = new javax.swing.JMenuItem();

            adm_menu.setText("Adm");
            addJogo_menuItem.setText("Adicionar Jogo");
            addJogo_menuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addJogo_menuItemActionPerformed(evt);
                }
            });
            adm_menu.add(addJogo_menuItem);

            removerJogo_menuItem.setText("Remover Jogo");
            removerJogo_menuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    removerJogo_menuItemActionPerformed(evt);
                }
            });
            adm_menu.add(removerJogo_menuItem);

            Menu.add(adm_menu);
        }

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameboxd_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jogos_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barraDePesquisa_textfield)
                        .addGap(11, 11, 11)
                        .addComponent(btn_buscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(gameboxd_tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraDePesquisa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addGap(18, 18, 18)
                .addComponent(jogos_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listas_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listas_menuItemActionPerformed
        new ListasFrame(u);
    }//GEN-LAST:event_listas_menuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int res = JOptionPane.showConfirmDialog(
            null,
            "Tem certeza que deseja sair?",
            "Sair",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if(res == 0) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        refresh();
    }//GEN-LAST:event_formWindowActivated

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if(barraDePesquisa_textfield.getText().equals("")) {
            jogos = c.getJogos();
        } else {
            try {
                jogos = c.buscaJogos(barraDePesquisa_textfield.getText());
            } catch(BuscaException e) {
                JOptionPane.showMessageDialog(
                            null,
                            e.getMessage(),
                            "Aviso!",
                            JOptionPane.WARNING_MESSAGE
                    );
            } catch(Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
        refresh();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void conta_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conta_menuItemActionPerformed
        new MinhaConta(this.u, this);
    }//GEN-LAST:event_conta_menuItemActionPerformed

    private void minhasAvaliacoes_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasAvaliacoes_menuItemActionPerformed
        new MinhasAvaliacoes(u);
    }//GEN-LAST:event_minhasAvaliacoes_menuItemActionPerformed
    
    private void addJogo_menuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new AddJogoFrame(u);
    }
    
    private void removerJogo_menuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new RemoverJogoFrame();
        jogos = c.getJogos();
    }
    
    private javax.swing.JMenu adm_menu;
    private javax.swing.JMenuItem addJogo_menuItem;
    private javax.swing.JMenuItem removerJogo_menuItem;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JTextField barraDePesquisa_textfield;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JMenuItem conta_menuItem;
    private javax.swing.JLabel gameboxd_tittle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jogos_scrollPane;
    private javax.swing.JMenuItem listas_menuItem;
    private javax.swing.JMenuItem minhasAvaliacoes_menuItem;
    // End of variables declaration//GEN-END:variables
}
